import turtle
t=turtle.Turtle()
t.getscreen().bgcolor("orange")
t.speed(20)
t.penup()
t.left(180)
t.forward(350)
t.pendown()
for i in range(17):
        t.forward(30)
        t.left(170)
        t.forward(30)
t.penup()
t.right(190)
t.forward(90)
t.pendown()
t.write("Happy Teachers' Day Sir")
t.penup()
t.forward(530)
t.pendown()
for i in range(17):
        t.forward(30)
        t.left(170)
        t.forward(30)
turtle.done()